package com.mofei.tau.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mofei.tau.transaction.UTXORecord;
import com.mofei.tau.transaction.Key;
import com.mofei.tau.transaction.TransactionHistory;
import com.mofei.tau.db.greendao.User;

import com.mofei.tau.db.greendao.UTXORecordDao;
import com.mofei.tau.db.greendao.KeyDao;
import com.mofei.tau.db.greendao.TransactionHistoryDao;
import com.mofei.tau.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uTXORecordDaoConfig;
    private final DaoConfig keyDaoConfig;
    private final DaoConfig transactionHistoryDaoConfig;
    private final DaoConfig userDaoConfig;

    private final UTXORecordDao uTXORecordDao;
    private final KeyDao keyDao;
    private final TransactionHistoryDao transactionHistoryDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uTXORecordDaoConfig = daoConfigMap.get(UTXORecordDao.class).clone();
        uTXORecordDaoConfig.initIdentityScope(type);

        keyDaoConfig = daoConfigMap.get(KeyDao.class).clone();
        keyDaoConfig.initIdentityScope(type);

        transactionHistoryDaoConfig = daoConfigMap.get(TransactionHistoryDao.class).clone();
        transactionHistoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        uTXORecordDao = new UTXORecordDao(uTXORecordDaoConfig, this);
        keyDao = new KeyDao(keyDaoConfig, this);
        transactionHistoryDao = new TransactionHistoryDao(transactionHistoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(UTXORecord.class, uTXORecordDao);
        registerDao(Key.class, keyDao);
        registerDao(TransactionHistory.class, transactionHistoryDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        uTXORecordDaoConfig.clearIdentityScope();
        keyDaoConfig.clearIdentityScope();
        transactionHistoryDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public UTXORecordDao getUTXORecordDao() {
        return uTXORecordDao;
    }

    public KeyDao getKeyDao() {
        return keyDao;
    }

    public TransactionHistoryDao getTransactionHistoryDao() {
        return transactionHistoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
