package com.mofei.tau.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mofei.tau.transaction.UTXORecord;
import com.mofei.tau.transaction.KeyValue;
import com.mofei.tau.transaction.TransactionHistory;

import com.mofei.tau.db.greendao.UTXORecordDao;
import com.mofei.tau.db.greendao.KeyValueDao;
import com.mofei.tau.db.greendao.TransactionHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uTXORecordDaoConfig;
    private final DaoConfig keyValueDaoConfig;
    private final DaoConfig transactionHistoryDaoConfig;

    private final UTXORecordDao uTXORecordDao;
    private final KeyValueDao keyValueDao;
    private final TransactionHistoryDao transactionHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uTXORecordDaoConfig = daoConfigMap.get(UTXORecordDao.class).clone();
        uTXORecordDaoConfig.initIdentityScope(type);

        keyValueDaoConfig = daoConfigMap.get(KeyValueDao.class).clone();
        keyValueDaoConfig.initIdentityScope(type);

        transactionHistoryDaoConfig = daoConfigMap.get(TransactionHistoryDao.class).clone();
        transactionHistoryDaoConfig.initIdentityScope(type);

        uTXORecordDao = new UTXORecordDao(uTXORecordDaoConfig, this);
        keyValueDao = new KeyValueDao(keyValueDaoConfig, this);
        transactionHistoryDao = new TransactionHistoryDao(transactionHistoryDaoConfig, this);

        registerDao(UTXORecord.class, uTXORecordDao);
        registerDao(KeyValue.class, keyValueDao);
        registerDao(TransactionHistory.class, transactionHistoryDao);
    }
    
    public void clear() {
        uTXORecordDaoConfig.clearIdentityScope();
        keyValueDaoConfig.clearIdentityScope();
        transactionHistoryDaoConfig.clearIdentityScope();
    }

    public UTXORecordDao getUTXORecordDao() {
        return uTXORecordDao;
    }

    public KeyValueDao getKeyValueDao() {
        return keyValueDao;
    }

    public TransactionHistoryDao getTransactionHistoryDao() {
        return transactionHistoryDao;
    }

}
