package io.taucoin.android.wallet.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import io.taucoin.android.wallet.db.entity.ReferralInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REFERRAL_INFO".
*/
public class ReferralInfoDao extends AbstractDao<ReferralInfo, Long> {

    public static final String TABLENAME = "REFERRAL_INFO";

    /**
     * Properties of entity ReferralInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property InvitedReward = new Property(1, long.class, "invitedReward", false, "INVITED_REWARD");
        public final static Property FriendReward = new Property(2, long.class, "friendReward", false, "FRIEND_REWARD");
    }


    public ReferralInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ReferralInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REFERRAL_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"INVITED_REWARD\" INTEGER NOT NULL ," + // 1: invitedReward
                "\"FRIEND_REWARD\" INTEGER NOT NULL );"); // 2: friendReward
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REFERRAL_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReferralInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInvitedReward());
        stmt.bindLong(3, entity.getFriendReward());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReferralInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getInvitedReward());
        stmt.bindLong(3, entity.getFriendReward());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReferralInfo readEntity(Cursor cursor, int offset) {
        ReferralInfo entity = new ReferralInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // invitedReward
            cursor.getLong(offset + 2) // friendReward
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReferralInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInvitedReward(cursor.getLong(offset + 1));
        entity.setFriendReward(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReferralInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReferralInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReferralInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
