package com.mofei.tau.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mofei.tau.entity.Accounts;

import com.mofei.tau.db.greendao.AccountsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountsDaoConfig;

    private final AccountsDao accountsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountsDaoConfig = daoConfigMap.get(AccountsDao.class).clone();
        accountsDaoConfig.initIdentityScope(type);

        accountsDao = new AccountsDao(accountsDaoConfig, this);

        registerDao(Accounts.class, accountsDao);
    }
    
    public void clear() {
        accountsDaoConfig.clearIdentityScope();
    }

    public AccountsDao getAccountsDao() {
        return accountsDao;
    }

}
